### ISSUE TITLE
Linux distributions are very large

### ISSUE THREAD

**Issue by EndrII** [taskmaster9001/stegano#2]
Hi
i see your deployment documentation. You are using allQmDepends parameters. But this option added unnecessary qml libraries.
Remove this deployment command parameter and redeploy the project.

```
cqtdeployer -bin stegano  -qmldir ~/steganography/Steganography/ -targetDir ~/release/
```

**Comment by tm9k1** [comment]
oh! Thanks a lot for sharing, @EndrII ! I have never packaged any Qt project, this was a first for me. 😅
I'll fix that as soon as I can.

**Comment by EndrII** [comment]
thanks )

**Comment by tm9k1** [comment]
Hi again @EndrII !
I just tried the command, but it didn't bring along all the deps. Please take a look at the attached screenshot.

![linux error](https://user-images.githubusercontent.com/22996531/94982139-d5aa5100-0555-11eb-8aa2-91b513390983.png)

I got the exact same issue while releasing (without the flag `allQmlDependes`)  on Windows as well.

**Comment by EndrII** [comment]
You are using the wrong qmldir option. not **qmldir** but **qmlDir**

``` bash
cqtdeployer -bin myApp -qmlDir /path/to/my/qml/files -recursiveDepth 3 -targetDir ~/release/
```

And please add -recursiveDepth 3 parameter to recursively find qml files from path/path/to/my/qml/files

**Comment by tm9k1** [comment]
ah! so it didn't pick up on the qmlDir flag at all! It still made the release, wow! I'll fix this in the wiki and make a new release ASAP. The build size was halved when I tried this a couple minutes ago. Crazy!
P.S: @EndrII I see a contribution opportunity here. Would you mind if I add a check to CQtDeployer for erroring when an unidentified flag (like -qmldir) is passed?

**Comment by EndrII** [comment]
@taskmaster9001 thanks you. i am very happy of any help. 
when i looked at this post i thought the same thing. We need to add support for displaying invalid options.
I will create a task for you, where I will describe what and how best to do,

**Comment by tm9k1** [comment]
Great! Looking forward to it ^_^

**Comment by EndrII** [comment]
it is done )
see this [issue](https://github.com/QuasarApp/CQtDeployer/issues/421)
